// color for each state
const colors = {
    "AL": "#E0B3FF",
    "AK": "#F5F5F5",
    "AZ": "#FDDFDF",
    "AR": "#E6E6E6",
    "CA": "#FFCC66",  // "#FFB3A3",
    "CO": "#FFFFE0",
    "CT": "#FFFDB3",
    "DE": "#FFCCB3",
    "FL": "#B3FFF5",
    "GA": "#D9FFDB",
    "HI": "#85C1E9", // "#B3FFF5",
    "ID": "#FFFAE6",
    "IL": "#FFCCFF",
    "IN": "#FFCCCC",
    "IA": "#FFFDB3",
    "KS": "#B3FFD9",
    "KY": "#FFF5B3",
    "LA": "#E5E5E5",
    "ME": "#E0CCFF",
    "MD": "#D9D9D9",
    "MA": "#B3E5FF",
    "MI": "#E6FFB3",
    "MN": "#B3FFF5",
    "MS": "#B3FFCC",
    "MO": "#FFD9DC",
    "MT": "#B3F5FF",
    "NE": "#CCB3FF",
    "NV": "#FFB3D9",
    "NH": "#B3FFF0",
    "NJ": "#FFD9DC",
    "NM": "white",
    "NY": "#CCB3FF",
    "NC": "#DEFDE0",
    "ND": "#E6E0D4",
    "OH": "#FFEEDD",  // "#FFE5B3",
    "OK": "#D9FFB3",
    "OR": "#B3A9FF",  // "#B3ECFF",
    "PA": "#FFD9B3",
    "RI": "#F5F5F5",
    "SC": "#EAEDA1",
    "SD": "#F8D5A3",
    "TN": "#98D7A5",
    "TX": "#FFFFE0",
    "UT": "#FFB3B3",
    "VT": "#FCEAFF",
    "VA": "#F4E7DA",
    "VI": "#66CCFF", 
    "WA": "#86E3FF",  // "#B3FFFA",
    "WV": "#DEF3FD",
    "WI": "#FCF7DE",
    "WY": "#B3D9FF"
};

export { colors };